# Generated by Django 3.2 on 2021-04-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bankName',
            new_name='name',
        ),
    ]
