# Generated by Django 3.2 on 2021-04-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_channelcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelcategory',
            name='icon',
            field=models.ImageField(upload_to='category'),
        ),
    ]
